[package]
name = "discovery"
version = "0.1.0"
edition = "2021"
rust-version = "1.80"
license = "MPL-2.0"
publish = false

[build-dependencies]
hot-reload = { path = "../hot-reload/rust" }
# No direct dependency on godot crate.